config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get "pages/about", to: "pages#about"
  get "pages/contact", to: "pages#contact"

  resources :posts do
    resources :comments
  end

  root "pages#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  primary_abstract_class

  scope :by_recently_updated, -> { order(updated_at: :desc) }

  def posted_time_passed
    if self.updated_at - self.created_at > 1
      "Edited " + time_ago_in_words(self.updated_at) + " ago"
    else
      "Posted " + time_ago_in_words(self.created_at) + " ago"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, allow_blank: false

  belongs_to :post
  belongs_to :user
  broadcasts_to :post

  def commented_time_ago
    posted_time_passed.downcase.split(" ").drop(1).join(" ")
  end

  scope :approved, -> { where.not(approved_at: nil) }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true, allow_blank: false

  belongs_to :user

  has_rich_text :body
  has_many :comments, dependent: :destroy

  def body_joined_text
    return first_body if first_body == last_body

    [first_body, last_body].join(" ").squeeze(" ")
  end

  def first_body
    body_text&.first&.squish
  end

  def last_body
    body_text&.last&.split("]")&.last&.squish
  end

  private

  def body_text
    self.body.to_plain_text.squish.split("[")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy

  def username
    if name.nil? || name == ""
      email_to_name
    else
      name
    end
  end

  private

  def email_to_name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create ]
  before_action :set_post

  def create
    comment = @post.comments.create(comment_params)

    if comment.save
      flash[:notice] = "Comment was successfully posted"
      redirect_to @post
      CommentsMailer.submitted(comment).deliver_later
    else
      flash[:alert] = "Comment failed to post #{comment.errors.full_messages}"
      redirect_to @post
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body).merge(user: current_user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.by_recently_updated
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body).merge(user: current_user)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 500, 500 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <div class="comment-body">
    <h6><%= comment.user.username %></h6>
    <p class="text-wrap"><%= comment.body %>
      — <small><%= comment.commented_time_ago %></small>
    </p>
    <span class="hor-divider"></span>
  </div>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ post, post.comments.build ] do |form| %>
  <%= form.text_area :body, size: "30x3", placeholder: "Add a comment..." %>
  <%= form.submit class: "btn btn-primary btn-sm" %>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Ekklesia", root_path, class: "navbar-brand font-monospace fs-4" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", pages_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogs", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", pages_contact_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= render "user/session_manager" %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Ekklesia Church</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous">
    </script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
      <div class="container">
        <%= render "layouts/alerts" %>
      </div>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1 class="display-4 font-monospace mb-3 fw-bold">About Us</h1>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1 class="display-4 font-monospace mb-3 fw-bold">Contact Us</h1>
</div>

app/views/pages/index.html.erb
<div class="homepage">
  <div class="homepage_content">
    <div class="homepage_title text-center text-uppercase">
      <h1 class="display-2 fw-bold">Ekklesia</h1>
      <h1 class="display-2 fw-lighter">Church</h1>
      <%= link_to "See Activities",
        posts_path,
        class: "text-decoration-none btn btn-light btn-lg mt-4 text-capitalize"
      %>
    </div>
  </div>
</div>

app/views/posts/_comments.html.erb
<div class="card shadow mb-3">
  <div class="card-body">
    <h3>Comments</h3>

    <div id="comments">
      <%= render post.comments.approved.by_recently_updated %>
    </div>

    <%= render "comments/new", post: post if current_user %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(post.errors.count, "error") %>
        prohibited this post from being saved:
      </h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "d-block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :body, class: "d-block" %>
    <%= form.rich_text_area :body, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% if controller.action_name == "show" %>
  <div class="card shadow mb-3">
    <div class="card-body">
      <%= render "post_content", post: post %>
    </div>
  </div>
<% else %>
  <div class="mw-75">
    <%= render "post_content", post: post %>
  </div>
<% end %>

app/views/posts/_post_content.html.erb
<div class="post_content">
  <%= link_to post_path(post), class: "text-decoration-none text-dark" do %>
    <div id="<%= dom_id post %>">
      <p>
        <strong>Title:</strong>
        <%= post.title %>
      </p>

      <p>
        <small><%= post.posted_time_passed %></small>
      </p>

      <% if controller.action_name != "show" %>
        <p>
          <strong><%= pluralize(post.comments.approved.count, "comment") %></strong>
        </p>
      <% end %>

      <p>
        <strong>Body:</strong>
        <%# <p> %>
        <%#   <%= truncate(post.first_body, length: 450) %1> %>
        <%# </p> %>

        <% if controller.action_name != "show" %>
          <p class="post_images">
            <% post.body.embeds.first(3).each do |img| %>
              <%= image_tag img.blob, class: "post_image" %>
            <% end %>
          </p>

          <p>
            <%= truncate(post.body_joined_text, length: 800) %>
          </p>
        <% else %>
          <%= post.body %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="mb-4">
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <span class="display-4 font-monospace mb-3 fw-bold">Posts</span>
    <%= link_to "New Post", new_post_path, class: "btn btn-primary" if Rails.env.development? && current_user&.admin %>
  </div>

  <div id="posts">
    <% @posts.each do |post| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <%= render post %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<%= link_to "Back to posts", posts_path, class: "btn btn-outline-secondary" %>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>

<div class="container mb-4">
  <div class="d-flex justify-content-between align-items-center">
    <span class="d-inline-block display-4 font-monospace mb-3 fw-bold">Post</span>
    <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" if Rails.env.development? && current_user&.admin %>
  </div>

  <%= render @post %>

  <%# <%= render "posts/comments", post: @post %1> %>

  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
</div>

app/views/user/_session_manager.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a
      class="nav-link dropdown-toggle"
      href="#"
      id="navbarDropdown"
      role="button"
      data-bs-toggle="dropdown"
      aria-expanded="false">
      <%= current_user.username %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li class="dropdown-item"><%= current_user.username %></li>
      <li>
        <%= link_to "Profile Settings",
          edit_user_registration_path,
          class: "dropdown-item"
        %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= button_to "Log Out",
          destroy_user_session_path,
          method: :delete,
          class: "dropdown-item"
        %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
  </li>
<% end %>